FROM node:12

ENV PORT 80

# Create app directory
WORKDIR /app

# Installing dependencies
COPY package.json .
RUN npm install

# Copying source files
COPY . .

# Building app
RUN npm run build
EXPOSE 80

# Running the app
CMD "npm" "run" "start"


