import Head from "next/head";

function DeclarationHeader() {
    return (
        <Head>
            <title>ReactJS-application dockerization guide</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="author" content="Устинов Дмитрий" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
    );
}

export default DeclarationHeader;
